# Project information
site_name: 'Cyber Playbook'
site_description: 'Playbooks are used by cybersecurity professionals to store or encapsulate knowledge on cybersecurity topics and tactics.'
site_author: 'Randy Rowland'
site_url: 'https://rowland007.github.io/Cyber-Playbook/'

# Repository
repo_name: 'Randy Rowland'
repo_url: 'https://github.com/rowland007/'

# Copyright
copyright: 'Copyright &copy; 2021-2022 Randall Rowland<br>This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

# Navigation Menu
nav:
    - Overview: 'index.md'
    - Component Security:
        'Overview': 'component/index.md'
        'Data Management Life Cycle': 'component/data-manage-life.md'
    - Connection Security:
        'Overview': 'connection/index.md'
        'IPv4 Subnets': 'connection/ip4-subnets.md'
        'IPv6 References': 'connection/ip6-references.md'
        'Cisco IOS Commands': 'connection/cisco-commands.md'
    - Data  Security:
        'Overview': 'data/index.md'
    - Human Security:
        'Overview': 'human/index.md'
    - Organizational Security:
        'Overview': 'organizational/index.md'
        'A Common Language for Computer Security Incidents': 'organizational/common-language-for-computer-security-incidents.md'
    - Societal Security:
        'Overview': 'societal/index.md'
    - Software Security:
        'Overview': 'software/index.md'
        'OWASP Top 10 Proactive Controls': 'software/owasp-top-ten-pro-cntrls.md'
    - System Security:
        'Overview': 'system/index.md'
        'CIS Controls': 'system/cis-controls.md'
        'PowerShell Example Scripts': 'system/ps-sample-scripts.md'
        'Protecting CUI': 'system/nist-800-18.md'
        'OWASP Best Practices: Use of WAF': 'system/owasp-waf.md'
        '10 Things Auditors Should Know': 'system/10-things-auditors.md'
    - Glossary: 
        'Cybersecurity Terms': 'glossary.md'
        'Basic Cryptography': 'cryptography.md'
        'Basic Scripting and Programming': 'programming.md'
        'Policy and Compliance': 'compliance.md'
        'Privacy': 'privacy.md'
    - Appendix 1 - Resources: 'resources.md'

# Configuration
theme:
  name: material
  palette:
    primary: blue
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library

# Customization
extra:
  social:
    - icon: material/cloud
      link: https://randyrowland.me
    - icon: fontawesome/brands/github
      link: https://github.com/rowland007
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/randarxj7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/randall-rowland-jr
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/rowland007

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg